### ISSUE TITLE
Thanks for the code, possible improvements?

### ISSUE THREAD

**Issue by YahyaAbraheem** [akash13singh/mxnet-for-cdl#1]
Thanks again,

What could be possible future improvements on your code? Is there anyway to optimize it? Or you think this is an optimized code?

**Comment by akash13singh** [comment]
Hey
Sorry for the late reply, I was busy with coursework and did not look at this. I think a lot of optimizations are possible. This code is based on the demo code provided by the author. For example there is no pre-training. Also it might be worth comparing only the results of only the matrix factorization component and the CDL. This would give an idea how much does the deep learning component helps.
