### ISSUE TITLE
Hello, why you don't use sigmoid instead of relu?

### ISSUE THREAD

**Issue by YahyaAbraheem** [akash13singh/mxnet-for-cdl#2]
Why you used sigmoid instead of relu?

**Comment by akash13singh** [comment]
Hey  
Actually I tried sigmoid, but there wasn't any improvement and the training took a bit longer. By did only 1 run. It might be worth trying again.

**Comment by YahyaAbraheem** [comment]
Thanks a lot akash. I am trying to add side information to the code? There has been a discussion that this will enhance the results, to what extent do you agree?
